version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    volumes:
      - ./server:/server

  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client

  mongo:
    image: mongo:latest
    restart: always
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
